version: '3'
services:
  jupyterlab:
    build: ./docker/jupyterlab
    ports:
      - "6543:8888"
    volumes: 
      - ./notebooks:/home/jovyan/work/notebooks
      - ./pyscripts:/home/jovyan/work/pyscripts
      - ./metadata:/home/jovyan/work/metadata
      - ./data:/home/jovyan/work/data
    user: root
    environment:
      - PYTHONPATH=/home/jovyan/work:$PYTHONPATH
    command: jupyter lab --no-browser --allow-root

  mapping:
    build: ./docker/mapping
    volumes:
      - ./data:/data
      - ./metadata:/metadata
      - ./scripts:/scripts

  blast:
    image: ncbi/blast:2.11.0
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  kofamscan:
    build: ./docker/kofamscan
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - /nfs_share/yamanouchi/kofamscan210324:/db

  gtdbtk:
    image: ecogenomic/gtdbtk:1.5.0
    volumes:
      - ./data:/data
      - /nfs_share/yamanouchi/gtdb/release202:/refdata

