FROM continuumio/miniconda3:4.9.2
RUN conda install -c conda-forge -y mamba==0.8.2
RUN mamba install -c conda-forge -c bioconda -y \
        sra-tools==2.11.0 fastp==0.20.1 bowtie2==2.4.4 samtools==1.12  

